name: automated-tests
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches: [$default-branch, main]
       

jobs: 
  run_script:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with: 
          node-version: '16'

      - name: Setting up variables
        run: |
             echo "default-branch=${GITHUB_REF#refs/heads/}"
             echo "default-branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
  
      - name: Yarn installation
        run: |
             npm i -g corepack
             yarn install

      - name: Running jest script
        run: yarn run tests
