name: Todo Web CI/CD

on:
    push:
        branches: [deploy]
    pull_request:
        branches: [deploy, main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Clone repository
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Installing dependecies...
              run: yarn 
            - name: Testing the app...
              run: yarn test
            - name: Building the app...
              run: yarn run build
            - name: "Message"
              run: echo "Success"
