on:
    push:
        branches: [deploy]
    pull_request:
        branches: [deploy]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - name: Clone repository
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Installing dependecies...
              run: npm i
            - name: Testing the app...
              run: npm test
            - name: Building the app...
              run: npm run build
